# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf050d5558f33109ab58a599eaa432a99328cbd5f919b268b1ea9c2abad187f5cf1708937dac661036836014f52121bbb61a48fa52ef1b8f30bfd17ddbaf893

test:
  secret_key_base: e8d07b3f6220e91ffd26a80029dfcf353fdb0c6d7514d56eac97a4d60a999817127a1834090ae90c3c7be6f89a5363ca5538fbed91d269f20b04a5090621c206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
